.TH EDUGRP.CH 7
.SH NAME
edugrp.ch \- Swiss
.B ed(1)
user group
.SH DESCRIPTION
eudgrp.ch is the Ed User Group Switzerland, the one and only user group for the text editor 
.B ed(1)
in Switzerland.
.PP
.B ed(1)
is the standard unix text editor.
.SH HISTORY
The Ed User Group Switzerland was founded in November 2019 by two reactionary Computer Science students at
.URL www.hslu.ch HSLU .
They had too much exposure of professors suggesting to use NetBeans instead of
.B vim(1),
so the students decided to head for the other direction instead.
